Sol.Ventas.ClienteMVC/Models/ErrorViewModel.cs
using System;

namespace Sol.Ventas.ClienteMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sol.Ventas.ClienteMVC/Controllers/ArticuloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sol.Ventas.ClienteMVC.Filtros;
using Sol.Ventas.DTO;
using Sol.Ventas.Services;

namespace Sol.Ventas.ClienteMVC.Controllers
{
    //[AutenticaBasicoFilter]
    public class ArticuloController : Controller
    {
        private IArticuloServices _services;
        public ArticuloController(IArticuloServices services)
        {
            _services = services;
        }

        public IActionResult Index(string miFiltro = "")
        {
            List<Articulo> lista = _services.Listar();
            if (!string.IsNullOrEmpty(miFiltro))
            {
                lista = lista.Where
                    (t => t.Nombre.ToUpper().Contains(miFiltro.ToUpper())).ToList();
            }

            bool esAsincrono = false;
            string res = Request.Headers["X-Requested-With"];


            if (!string.IsNullOrEmpty(res) && res == "XMLHttpRequest")
            {
                esAsincrono = true;
            }

            if (esAsincrono)
            {
                return PartialView("_ListaArticulo", lista);
            }
            else
            {
                return View(lista);
            }
            

            //return View(new List<Articulo>());
        }
        [HttpGet]
        public IActionResult EditarParcial(int id=0)
        {
            Articulo a;

            if (id == 0) //nuevo
            {
                a = new Articulo();
            }
            else //editar
            {
                a = _services.Recuperar(id);
            }
            return PartialView("_EditarArticulo", a);
        }
        [HttpGet]
        public JsonResult GrabarParcial(Articulo a)
        {
            try
            {
                if (a.Codigo == 0)
                {
                    _services.Insertar(a);
                }
                else
                {
                    _services.Actualizar(a);
                }
                return Json(new { res = 1 });
            }
            catch(Exception ex)
            {
                return Json(new { res = 0, mensaje = ex.Message });
            }
        }
        [HttpGet]
        public IActionResult Editar(int id = 0)
        {
            Articulo a;

            if (id == 0) //nuevo
            {
                a = new Articulo();
            }
            else //editar
            {
                a = _services.Recuperar(id);
            }
            return View(a);

        }

        [HttpPost]
        public IActionResult Grabar(Articulo a)
        {
            if (a.Codigo == 0)
            {
                _services.Insertar(a);
            }
            else
            {
                _services.Actualizar(a);
            }

            return RedirectToAction("Index");
        }

        public JsonResult Eliminar(int id) {
            try
            {
                _services.Eliminar(id);
                return Json(new { res = "1" });
            }
            catch (Exception ex)
            {
                return Json(new { res = "0", detalle = ex.Message });
            }

        }

    }
}

Sol.Ventas.ClienteMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sol.Ventas.ClienteMVC.Models;

namespace Sol.Ventas.ClienteMVC.Controllers
{
    //[Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sol.Ventas.ClienteMVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Sol.Ventas.DTO;
using Sol.Ventas.Services;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace Sol.Ventas.ClienteMVC.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUsuarioServices _Services;
        private readonly SignInManager<IdentityUser> manager;

        public LoginController(
            IUsuarioServices _services,
            SignInManager<IdentityUser> manager
            )
        {
            _Services = _services;
            this.manager = manager;
        }
        [HttpGet]
        public IActionResult Index()
        {

            Usuario u = new Usuario();
            return View(u);
        }

        [HttpPost]
        public IActionResult Index(Usuario user)
        {
            Usuario u = _Services.Autenticar(user.Login, user.Clave);
            if (u == null)
            {
                ModelState.AddModelError("*", "Credenciales invalidas");
                return View(u);
            }
            else
            {
                //grabarlo en sesion 
                HttpContext.Session.SetString("login", u.Login);
                u.Clave = "";
                string usuariotexto = JsonConvert.SerializeObject(u);
                HttpContext.Session.SetString("user", usuariotexto);
                return RedirectToAction("Index", "Home");
            }

        }

        public IActionResult CerrarSesion()
        {

            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Login");
        }

        public IActionResult LoginGoogle()
        {
            //Enviar a google
            string urlRetorno = Url.Action("GoogleResponse", "Login");
            var propiedades =
                manager.ConfigureExternalAuthenticationProperties
                    ("Google", urlRetorno);
            return new ChallengeResult("Google", propiedades);
        }

        public async Task<IActionResult> GoogleResponse()
        {
            //recibir de google
            ExternalLoginInfo res = await manager.GetExternalLoginInfoAsync();
            string correo = res.Principal.Claims.ElementAt(4).Value;
            string nombre = res.Principal.Claims.ElementAt(2).Value;
            Usuario u = new Usuario()
            {
                Clave = "",
                Origen = "GMAIL",
                Login = correo,
                NombreCompleto = nombre
            };
            Usuario u2 = _Services.Insertar(u);
            HttpContext.Session.SetString("login", u2.Login);
            u.Clave = "";
            string usuariotexto = JsonConvert.SerializeObject(u2);
            HttpContext.Session.SetString("user", usuariotexto);
            return RedirectToAction("Index", "Home");
        }
    }
}

Sol.Ventas.ClienteMVC/Views/Articulo/Editar.cshtml
@model Sol.Ventas.DTO.Articulo

@{
    ViewData["Title"] = "Editar";
}

@if (Model.Codigo == 0)
{
    <h1>Nuevo Articulo</h1>
}
else
{
    <h1>Editar articulo: @Model.Nombre</h1>
}



<h4>Articulo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @*@this.Html.ActionLink("Haga clic", "Index")
        <a asp-action="Index">Haga clic</a>
        <a href="/Index">Haga clic</a>*@

        <form asp-action="Grabar" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                @*<input type="text" class="form-control"
                       name="Nombre" id="Nombre" value="@Model.Nombre"
                       />*@
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label for="Nombre" class="control-label">Nombre</label>*@
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                @*<input type="text" class="form-control"
                       name="Precio" id="Precio" value="@Model.Precio" />*@
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" onclick="saludar()" class="btn btn-primary">Save</button>
                <button type="button" id="btnValida" class="btn btn-warning">Validar Datos</button>
                @*<input type="submit" value="Save" class="btn btn-primary" />*@
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<div id="seccion1">

</div>
<script>
    $(document).ready(function () {
        $("#btnValida").click(function () {
            var precio = $("#Precio").val();
            //var precio = document.getElementById("Precio").value;
            alert("Hola mundo " + precio);
            $.get(
                "/articulo/index",
                function (resultado) {
                    $("#seccion1").html(resultado);
                })
        })
    })
</script>

Sol.Ventas.ClienteMVC/Views/Articulo/Index.cshtml
@model IEnumerable<Sol.Ventas.DTO.Articulo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form data-ajax="true" data-ajax-update="#divLista" id="frmLista">
    <div class="form-group ">
        <label for="txtFiltro">Filtro por Nombre</label>
        <div class="input-group">
            <input type="text" name="miFiltro" id="txtFiltro" placeholder="ingrese el filtro" class="form-control">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-info btn-flat">
                    <i class="fa fa-search"></i>
                    Buscar
                </button>
                <a asp-action="Editar" class="btn btn-info btn-flat">
                    <i class="fa fa-minus"></i>  Agregar
                </a>
                <button type="button" data-url="/articulo/editarparcial?id=0" class="btn btn-info btn-flat modalGalaxy">Nuevo Modal</button>
            </span>
        </div>
    </div>
    <div id="divLista">
        @await Html.PartialAsync("_ListaArticulo", Model)
    </div>

</form>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal"  data-target="#exampleModal">
    Launch demo modal
</button>

Sol.Ventas.ClienteMVC/Views/Articulo/_EditarArticulo.cshtml
@model Sol.Ventas.DTO.Articulo

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" >
            @if (Model.Codigo == 0)
            {
                <text>Agregar Articulo</text>
            }
            else
            {
                <text>Editar @Model.Nombre</text>
            }
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-12">
                    <form asp-action="_EditarArticulo">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row form-horizontal">
                            <div class="col-12">
                                <div class="form-group">
                                    <label asp-for="Codigo" class="control-label col-3"></label>
                                    <div class="col-12">
                                        <input asp-for="Codigo" class="form-control" />
                                        <span asp-validation-for="Codigo" class="text-danger"></span>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label asp-for="Nombre" class="control-label"></label>
                            <input asp-for="Nombre" class="form-control" />
                            <span asp-validation-for="Nombre" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Precio" class="control-label"></label>
                            <input asp-for="Precio" class="form-control" />
                            <span asp-validation-for="Precio" class="text-danger"></span>
                        </div>
                        @*<div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>*@
                    </form>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="btnGrabar">Grabar</button>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#btnGrabar").click(function () {
            var res = confirm("¿Estas Seguro?");
            if (res) {
                var art = {
                    Codigo: $("#Codigo").val(),
                    Nombre: $("#Nombre").val(),
                    Precio: $("#Precio").val()
                }
                $.getJSON("/articulo/grabarparcial",
                    art,
                    function (resp) {
                        if (resp.res == 1) {
                            alert("Datos grabados correctamente");
                            parent.cerrarModal();
                        } else {
                            alert("No se puedo grabar: " + resp.mensaje);
                        }
                    })
            }
        })
    })
</script>

Sol.Ventas.ClienteMVC/Views/Articulo/_ListaArticulo.cshtml
@model IEnumerable<Sol.Ventas.DTO.Articulo>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                <td>
                    @Html.ActionLink("Edicion", "Editar", new { id = item.Codigo }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    <button class="btn btn-primary"
                            onclick="eliminar(@item.Codigo)">
                        Eliminar
                    </button>
                    <button class="btn btn-primary modalGalaxy"
                            data-url="/articulo/editarparcial?id=@item.Codigo">
                        Editar
                    </button>

                </td>
            </tr>
        }
    </tbody>
</table>


<script>
    function eliminar(codigo) {

        var confirma = confirm("seguro de eliminar?");
        if (!confirma) {
            return;
        }
            $.getJSON(
                "@Url.Action("Eliminar", "Articulo")",
                { id: codigo }, function (rpta) {
                    if (rpta.res == "1") {
                        alert("Datos grabados correctamente");
                        $("#frmLista").submit();
                    }
                    else {
                        alert("Hubo error: " + rpta.detalle);
                    }
                })
        }
</script>

Sol.Ventas.ClienteMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Sol.Ventas.ClienteMVC/Views/Login/Index.cshtml
@model Sol.Ventas.DTO.Usuario

@{
    ViewData["Title"] = "Index";
}

 
<h4>Ingrese credenciales</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>


            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clave" class="control-label"></label>
                <input type="password" asp-for="Clave" class="form-control" />
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>
            @if (!ViewData.ModelState.IsValid)
            {
                <div class="form-group has-feedback">
                    @Html.ValidationSummary(false, "Se encontro errores")
                </div>
            }

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        <form asp-action="LoginGoogle">
            <div class="form-group">
                <input type="submit" value="Usa Google" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>
 

Sol.Ventas.ClienteMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor accesor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sol.Ventas.ClienteMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery.unobtrusive-ajax.js"></script>
    @RenderSection("Scripts", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sol.Ventas.ClienteMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (accesor.HttpContext.Session.GetString("user") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login"
                                   asp-action="CerrarSesion">Cerrar Sesion</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login"
                                   asp-action="Index">Iniciar Sesion</a>
                            </li>   
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <!-- Modal -->
        <div class="modal fade in contenedor" id="contenedor" data-backdrop="static" data-keyboard="true" >
            <div class="seccionModal"></div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Sol.Ventas.ClienteMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

  
</body>
</html>